# Import Library

In [70]:
import os
import re
import joblib
import numpy as np
import pandas as pd

from pathlib import Path

from nltk.tokenize import word_tokenize

# Config

In [71]:
# =========================
# CONFIGURATION
# =========================

SCENARIO = 4

"""
1 : TF-IDF + Naive Bayes
2 : TF-IDF + SVM
3 : FastText + SVM
4 : IndoBERT
"""

# 0 = Full
# 1 = 10k
# 2 = 20k
# 3 = 30k
# 4 = 40k

CORPUS_SIZE = 4
CORPUS_MAP = {
    0:"full",
    1:"10k",
    2:"20k",
    3:"30k",
    4:"40k"
}
DATASET_NAME = CORPUS_MAP[CORPUS_SIZE]

print()

print("Scenario :", SCENARIO)
print("Corpus   :", DATASET_NAME)

Scenario : 4
Corpus   : 40k

In [72]:
CONFIG = {

    1:{
        "name":"tfidf_nb",
        "vectorizer": f"vectorizers/skenario 1/tfidf_nb_vectorizer_{DATASET_NAME}.joblib",
        "model":f"models/skenario 1/tfidf_nb_{DATASET_NAME}.joblib"
    },

    2:{

        "name":"tfidf_svm",
        "vectorizer":f"vectorizers/skenario 2/tfidf_svm_vectorizer_{DATASET_NAME}.joblib",
        "model":f"models/skenario 2/tfidf_svm_{DATASET_NAME}.joblib"
    },

    3:{
        "name":"fasttext_svm",
        "embedding":f"models/skenario 3/fasttext_{DATASET_NAME}.joblib",
        "model":f"models/skenario 3/fasttext_svm_{DATASET_NAME}.joblib"
    },

    4:{
        "name":"indobert",
        "model_dir": f"models/skenario 4/indobert_{DATASET_NAME}"
    }

}

if SCENARIO not in CONFIG:
    raise ValueError("SCENARIO tidak valid!")

print()
print(CONFIG[SCENARIO])

{'name': 'indobert', 'model_dir': 'models/skenario 4/indobert_40k'}

# Load Data & Label Encoder

In [73]:
df = pd.read_csv("dataset/unseen.csv")
print()

print(df.shape)
display(df.head())

(300, 2)

                                               Tweet      Category
0       itulah yang saya rasakan tentang The Sandman  Entertaiment
1  Kompilasi video kecepatan 4x dari sesi gacha 4...  Entertaiment
2  Jadwal MPL ID S17 Week 8 Hari Ini: Dewa United...    Technology
3  SALAH SATU PENYEBAB KEMISKINAN BUKAN KARENA KE...       Economy
4  bayangkan jika setiap serial animasi meningkat...  Entertaiment

In [74]:
def preprocess_text(text):

    text = str(text).lower()

    text = re.sub(

        r"https?://\S+|www\.\S+",

        " ",

        text

    )

    text = re.sub(

        r"@\w+",

        " ",

        text

    )

    text = re.sub(

        r"#",

        "",

        text

    )

    text = re.sub(

        r"\s+",

        " ",

        text

    )

    return text.strip()

df["text_clean"] = df["Tweet"].apply(preprocess_text)

In [75]:
le = joblib.load("dataset/preprocessed/label_encoder.pkl")

print()
print("Preprocessing Completed!")

display(
    df[[
            "Category",
            "text_clean"
        ]].head()
)

Preprocessing Completed!

c:\Users\user1\miniconda3\envs\nlp-gpu\lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.6.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

       Category                                         text_clean
0  Entertaiment       itulah yang saya rasakan tentang the sandman
1  Entertaiment  kompilasi video kecepatan 4x dari sesi gacha 4...
2    Technology  jadwal mpl id s17 week 8 hari ini: dewa united...
3       Economy  salah satu penyebab kemiskinan bukan karena ke...
4  Entertaiment  bayangkan jika setiap serial animasi meningkat...

# Scenario 1

In [76]:
if SCENARIO == 1:

    vectorizer = joblib.load(CONFIG[1]["vectorizer"])
    model = joblib.load(CONFIG[1]["model"])
    X = vectorizer.transform(df["text_clean"])
    pred = model.predict(X)

    print()
    print("TF-IDF + Naive Bayes Loaded!")

# Scenario 2

In [77]:
if SCENARIO == 2:

    vectorizer = joblib.load(CONFIG[2]["vectorizer"])
    model = joblib.load(CONFIG[2]["model"])
    X = vectorizer.transform(df["text_clean"])
    pred = model.predict(X)

    print()
    print("TF-IDF + SVM Loaded!")

# Scenario 3

In [78]:
def sentence_vector_fasttext(
    tokens,
    model,
    vector_size=300
):
    vectors = []
    for token in tokens:
        if token in model.wv:
            vectors.append(model.wv[token])

    if len(vectors) == 0:
        return np.zeros(vector_size)

    return np.mean(vectors, axis=0)

In [79]:
if SCENARIO == 3:

    ft_model = joblib.load(CONFIG[3]["embedding"])
    svm_model = joblib.load(CONFIG[3]["model"])
    tokens = [
        word_tokenize(text)
        for text in df["text_clean"]
    ]

    X = np.array([
        sentence_vector_fasttext(
            token,
            ft_model
        )
        for token in tokens
    ])

    pred = svm_model.predict(X)

    print()
    print("FastText + SVM Loaded!")

# Scenario 4

In [80]:
if SCENARIO == 4:

    import torch
    from transformers import (
        AutoTokenizer,
        AutoModelForSequenceClassification
    )

    MODEL_PATH = CONFIG[4]["model_dir"]
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)
    model.eval()

    pred = []
    for text in df["text_clean"]:
        inputs = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=128
        )

        with torch.no_grad():
            outputs = model(
                **inputs
            )

        label = torch.argmax(
            outputs.logits,
            dim=1
        )

        pred.append(label.item())

    pred = np.array(pred)

    print()
    print("IndoBERT Loaded!")

IndoBERT Loaded!

# Decode Prediction

In [81]:
df["prediction"] = le.inverse_transform(pred)
print()
print("Prediction Completed!")

display(
    df[[
        "Tweet",
        "prediction"
        ]]
)

Prediction Completed!

                                                 Tweet     prediction
0         itulah yang saya rasakan tentang The Sandman  Entertainment
1    Kompilasi video kecepatan 4x dari sesi gacha 4...     Technology
2    Jadwal MPL ID S17 Week 8 Hari Ini: Dewa United...     Technology
3    SALAH SATU PENYEBAB KEMISKINAN BUKAN KARENA KE...        Economy
4    bayangkan jika setiap serial animasi meningkat...     Technology
..                                                 ...            ...
295  Era AI membutuhkan CPU baru. Perkenalkan NVIDI...     Technology
296  Pertumbuhan ekonominya tinggi tapi yang tumbuh...        Economy
297  Integrasi Jaringan XLSmart Capai 70%  Sinyal 5...     Technology
298                    dia benar-benar menjadi ibunya.  Entertainment
299  SpaceX Ternyata Bakar Duit Besar-besaran dan R...     Technology

[300 rows x 2 columns]

# Result

In [82]:
display(df)
print()
print("Total Data :", len(df))

,Tweet,Category,text_clean,prediction
0,itulah yang saya rasakan tentang The Sandman,Entertaiment,itulah yang saya rasakan tentang the sandman,Entertainment
1,Kompilasi video kecepatan 4x dari sesi gacha 4...,Entertaiment,kompilasi video kecepatan 4x dari sesi gacha 4...,Technology
2,Jadwal MPL ID S17 Week 8 Hari Ini: Dewa United...,Technology,jadwal mpl id s17 week 8 hari ini: dewa united...,Technology
3,SALAH SATU PENYEBAB KEMISKINAN BUKAN KARENA KE...,Economy,salah satu penyebab kemiskinan bukan karena ke...,Economy
4,bayangkan jika setiap serial animasi meningkat...,Entertaiment,bayangkan jika setiap serial animasi meningkat...,Technology
...,...,...,...,...
295,Era AI membutuhkan CPU baru. Perkenalkan NVIDI...,Technology,era ai membutuhkan cpu baru. perkenalkan nvidi...,Technology
296,Pertumbuhan ekonominya tinggi tapi yang tumbuh...,Economy,pertumbuhan ekonominya tinggi tapi yang tumbuh...,Economy
297,Integrasi Jaringan XLSmart Capai 70% Sinyal 5...,Technology,integrasi jaringan xlsmart capai 70% sinyal 5g...,Technology
298,dia benar-benar menjadi ibunya.,Entertaiment,dia benar-benar menjadi ibunya.,Entertainment
299,SpaceX Ternyata Bakar Duit Besar-besaran dan R...,Technology,spacex ternyata bakar duit besar-besaran dan r...,Technology

Total Data : 300

Prediction Distirbution

In [83]:
prediction_summary = (
    df["prediction"]
    .value_counts()
    .sort_index()
    .reset_index()
)

prediction_summary.columns = [
    "Category",
    "Count"
]

display(prediction_summary)

        Category  Count
0        Economy    112
1  Entertainment     82
2     Technology    106

Save Prediction

In [84]:
os.makedirs("results/prediction", exist_ok=True)

MODEL_NAME = CONFIG[SCENARIO]["name"]

OUTPUT = (
    f"results/prediction/"
    f"{MODEL_NAME}_{DATASET_NAME}.csv"
)

df.to_csv(OUTPUT, index=False)

print()
print("Prediction Saved!")

print()
print(OUTPUT)

Prediction Saved!

results/prediction/indobert_40k.csv

Save summary

In [85]:
SUMMARY_OUTPUT = (
    f"results/prediction/"
    f"{MODEL_NAME}_{DATASET_NAME}_summary.csv"
)

prediction_summary.to_csv(SUMMARY_OUTPUT, index=False)

print()
print("Summary Saved!")

print()
print(SUMMARY_OUTPUT)

Summary Saved!

results/prediction/indobert_40k_summary.csv

Experiment Info

In [86]:
print()
print("="*50)
print("PREDICTION FINISHED")
print("="*50)

print()
print("Scenario :")
print(CONFIG[SCENARIO]["name"])

print()
print("Corpus :")
print(DATASET_NAME)

print()
print("Input Data :")
print(len(df))

print()
print("Prediction File :")
print(OUTPUT)

print()
print("Summary File :")
print(SUMMARY_OUTPUT)

print()
print("="*50)

==================================================
PREDICTION FINISHED
==================================================

Scenario :
indobert

Corpus :
40k

Input Data :
300

Prediction File :
results/prediction/indobert_40k.csv

Summary File :
results/prediction/indobert_40k_summary.csv

==================================================